---
abstract: 'Required attributes which fail only when trying to use them'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-LazyRequire
no_index:
  directory:
    - t
    - xt
requires:
  Carp: '0'
  Class::Method::Modifiers: '0'
  Sub::Quote: '0'
resources:
  IRC: irc://irc.perl.org/#moose
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MooX-LazyRequire
  license: http://dev.perl.org/licenses/
  repository: https://github.com/haarg/MooX-LazyRequire.git
version: '0.001000'
